8 series movies related
evoCampus/evowatch-backend pull request #27
Opened 2024-11-20 20:49 UTC by andraspazman

we created thius section  the controllers, services, dbo, dtos

2024-11-20 22:07 UTC, KercsiBence requested changes
- You should consult with @bqnce regarding the #26 task, think about the annotations. 
_https://learn.microsoft.com/en-us/ef/core/modeling/entity-properties?tabs=data-annotations%2Cwithout-nrt_
_https://learn.microsoft.com/en-us/ef/core/modeling/keys?tabs=data-annotations_
_https://learn.microsoft.com/en-us/ef/core/modeling/relationships/mapping-attributes_

- Remove unneccessary usings.
- Delete blank lines and multiple spaces.
- The code should be unified, somewhere modifiers like "virtual or required" are added, somewhere not. For mapping properties I'd use virtual.

2024-12-16 22:23 UTC, vadaszidavid requested changes
Please remove the extra blank lines

2025-01-13 19:15 UTC, KercsiBence requested changes

2025-01-19 14:32 UTC, vadaszidavid approved these changes

2025-01-20 20:13 UTC, KercsiBence approved these changes

2025-01-21 15:41 UTC, merged